POST http://127.0.0.1:5000/api/real
Content-Type: application/json

{
  "rro_id": 4000096193,
  "key_id": 8,
  "reals": [
    {
      "NAME": "Улыбка",
      "UNITNM": "шт",
      "AMOUNT": 2,
      "PRICE": 100,
      "COST": 200
    }
  ],
  "pays": [
    {
      "PAYFORMCD": 0,
      "PAYFORMNM": "Готівка",
      "SUM": 200
    }
  ],
    "taxes": [

  ]
}

###
