"""empty message

Revision ID: 00531cee29ce
Revises: 5f0144727371
Create Date: 2021-04-14 14:34:59.586665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00531cee29ce'
down_revision = '5f0144727371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='no_comments_yet'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    comment=' Промежуточная таблица которая показывает какие права доступны для какой роли '
    )
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True, comment='Ідентификатор текущей роли пользователя в системе'))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.drop_table('role_permission')
    # ### end Alembic commands ###
