"""empty message

Revision ID: 09d3796cd306
Revises: 3b968ff35ebd
Create Date: 2021-05-11 08:39:07.401870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09d3796cd306'
down_revision = '3b968ff35ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('z_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Идентификатор'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Идентификатор отделения'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='Идентификатор оператора'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='Время совершения операции'),
    sa.Column('rro_type', sa.String(length=4), nullable=True, comment='Тип РРО, що зараз використовується(rro, rkks, prro, none)'),
    sa.Column('rro_id', sa.String(length=16), nullable=True, comment='Идентификатор РРО привязанного до отделения'),
    sa.Column('z_number', sa.Integer(), nullable=True, comment='Номер Z отчета'),
    sa.Column('fn', sa.String(length=10), nullable=True, comment='Фискальный номер регистратора'),
    sa.Column('zn', sa.String(length=10), nullable=True, comment='Заводской номер регистратора'),
    sa.Column('fsn', sa.String(length=16), nullable=True, comment='Версия программы эквайера'),
    sa.Column('tn', sa.String(length=16), nullable=True, comment='Налоговый номер (EDRPOU)'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='Фискальный номер чека'),
    sa.Column('qr', sa.String(length=100), nullable=True, comment='Содержимое QR кода чека'),
    sa.Column('fiscal_time', sa.DateTime(), nullable=True, comment='Фискальное время чека'),
    sa.Column('op_cnt', sa.Integer(), nullable=True, comment='Количество операций в чеке'),
    sa.Column('sum_reinf', sa.Numeric(precision=20, scale=2), nullable=True, comment='Сумма подкреплений'),
    sa.Column('sum_collect', sa.Numeric(precision=20, scale=2), nullable=True, comment='Сумма инкассаций'),
    sa.Column('sum_adv', sa.Numeric(precision=20, scale=2), nullable=True, comment='Сумма авансов'),
    sa.Column('xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое отправляемого чека'),
    sa.Column('fiscal_xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое чека как его видит налоговая'),
    sa.Column('server_time', sa.DateTime(), nullable=True, comment='Время отправки на фискальный сервер (для пРРО)'),
    sa.Column('tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека'),
    sa.Column('fiscal_ticket', sa.TEXT(), nullable=True, comment='Текстовое содержимое ответа налоговой'),
    sa.Column('fiscal_error_code', sa.Integer(), nullable=True, comment='Код ошибки'),
    sa.Column('fiscal_error_txt', sa.TEXT(), nullable=True, comment='Текст ошибки'),
    sa.Column('shift_id', sa.Integer(), nullable=True, comment='Идентификатор смены'),
    sa.Column('printed', sa.Integer(), nullable=True, comment='Напечатано, количество раз'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment=' Таблица фискальных данных Z отчетов '
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('z_reports')
    # ### end Alembic commands ###
