"""empty message

Revision ID: 0ad60b4a68f3
Revises: 60242536c88c
Create Date: 2023-05-31 19:41:43.808991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ad60b4a68f3'
down_revision = '60242536c88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('prro_offline_session_id', sa.String(length=128), nullable=True, comment='Ідентифікатор офлайн сесії'))
    op.add_column('departments', sa.Column('prro_offline_seed', sa.String(length=128), nullable=True, comment='Секретне число для обчислення фіскального номера офлайн документа'))
    op.alter_column('departments', 'closed',
               existing_type=mysql.TINYINT(display_width=1),
               comment='ПРРО відключений у податковій',
               existing_comment='Стан ПРРО',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'closed',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Стан ПРРО',
               existing_comment='ПРРО відключений у податковій',
               existing_nullable=True)
    op.drop_column('departments', 'prro_offline_seed')
    op.drop_column('departments', 'prro_offline_session_id')
    # ### end Alembic commands ###
