"""empty message

Revision ID: 102d61566d9d
Revises: ebe49be57b9d
Create Date: 2021-12-12 14:40:00.405952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102d61566d9d'
down_revision = 'ebe49be57b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advances', sa.Column('storno_time', sa.DateTime(), nullable=True, comment='Время сторно'))
    op.add_column('advances', sa.Column('storno_tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека сторно'))
    op.add_column('inkasses', sa.Column('storno_time', sa.DateTime(), nullable=True, comment='Время сторно'))
    op.add_column('inkasses', sa.Column('storno_tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека сторно'))
    op.add_column('podkreps', sa.Column('storno_time', sa.DateTime(), nullable=True, comment='Время сторно'))
    op.add_column('podkreps', sa.Column('storno_tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека сторно'))
    op.add_column('sales', sa.Column('storno_time', sa.DateTime(), nullable=True, comment='Время сторно'))
    op.add_column('sales', sa.Column('storno_tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека сторно'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'storno_tax_id')
    op.drop_column('sales', 'storno_time')
    op.drop_column('podkreps', 'storno_tax_id')
    op.drop_column('podkreps', 'storno_time')
    op.drop_column('inkasses', 'storno_tax_id')
    op.drop_column('inkasses', 'storno_time')
    op.drop_column('advances', 'storno_tax_id')
    op.drop_column('advances', 'storno_time')
    # ### end Alembic commands ###
