"""empty message

Revision ID: 121d9a36cbd6
Revises: ae71f20ccde2
Create Date: 2022-02-08 14:39:40.038278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '121d9a36cbd6'
down_revision = 'ae71f20ccde2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_keys', sa.Column('encrypt_content', sa.String(length=1024), nullable=True, comment='Розпакований вміст ключа шифрування'))
    op.alter_column('department_keys', 'key_content',
               existing_type=mysql.VARCHAR(length=4096),
               comment='Розпакований вміст ключа підпису',
               existing_comment='Розпакований вміст сертифіката підпису',
               existing_nullable=True)
    op.alter_column('department_keys', 'cert1_content',
               existing_type=mysql.VARCHAR(length=4096),
               comment='Розпакований вміст сертифіката підпису',
               existing_comment='Розпакований вміст ключа',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department_keys', 'cert1_content',
               existing_type=mysql.VARCHAR(length=4096),
               comment='Розпакований вміст ключа',
               existing_comment='Розпакований вміст сертифіката підпису',
               existing_nullable=True)
    op.alter_column('department_keys', 'key_content',
               existing_type=mysql.VARCHAR(length=4096),
               comment='Розпакований вміст сертифіката підпису',
               existing_comment='Розпакований вміст ключа підпису',
               existing_nullable=True)
    op.drop_column('department_keys', 'encrypt_content')
    # ### end Alembic commands ###
