"""empty message

Revision ID: 19ef725b994d
Revises: b3ca900c244f
Create Date: 2021-05-24 20:22:09.032245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ef725b994d'
down_revision = 'b3ca900c244f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Отделение'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Пользователь'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='Время совершения операции'),
    sa.Column('shift_id', sa.Integer(), nullable=True, comment='Идентификатор смены'),
    sa.Column('fiscal_time', sa.DateTime(), nullable=True, comment='Время принятия фискальным сервером (для пРРО)'),
    sa.Column('server_time', sa.DateTime(), nullable=True, comment='Время отправки на фискальный сервер (для пРРО)'),
    sa.Column('sum', sa.Numeric(precision=20, scale=2), nullable=True, comment='Сумма'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='Локальный номер чека'),
    sa.Column('tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека'),
    sa.Column('xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое отправляемого чека'),
    sa.Column('fiscal_xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое чека как его видит налоговая'),
    sa.Column('fiscal_ticket', sa.TEXT(), nullable=True, comment='Текстовое содержимое ответа налоговой'),
    sa.Column('fiscal_error_code', sa.Integer(), nullable=True, comment='Код ошибки'),
    sa.Column('fiscal_error_txt', sa.TEXT(), nullable=True, comment='Текст ошибки'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о розничных продажах'
    )
    op.create_table('sales_check',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('sales_id', sa.Integer(), nullable=True, comment='Идентификатор операции'),
    sa.Column('code', sa.String(length=64), nullable=True, comment='Внутрішній код товару'),
    sa.Column('uktzed', sa.String(length=15), nullable=True, comment='Код товару згідно з УКТЗЕД'),
    sa.Column('name', sa.String(length=512), nullable=True, comment='Найменування товару, послуги або операції'),
    sa.Column('unitcd', sa.String(length=5), nullable=True, comment='Код одиниці виміру згідно класифікатора'),
    sa.Column('unitnm', sa.String(length=64), nullable=True, comment='Найменування одиниці виміру'),
    sa.Column('amount', sa.Numeric(precision=15, scale=3), nullable=True, comment='Кількість/об’єм товару'),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Ціна за одиницю товару'),
    sa.Column('letters', sa.String(length=15), nullable=True, comment='Літерні позначення видів і ставок податків/зборів'),
    sa.Column('cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='Сума операції'),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о платежах в розничных продажах'
    )
    op.create_table('sales_pays',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('sales_id', sa.Integer(), nullable=True, comment='Идентификатор операции'),
    sa.Column('type', sa.SmallInteger(), nullable=True, comment='Код форми оплати (числовий): 0–Готівка, 1–Банківська картка'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='Найменування виду податку/збору'),
    sa.Column('sum', sa.Numeric(precision=15, scale=2), nullable=True, comment='Загальна сума'),
    sa.Column('provided', sa.Numeric(precision=15, scale=2), nullable=True, comment='Сума внесених коштів'),
    sa.Column('remains', sa.Numeric(precision=15, scale=2), nullable=True, comment='Решта'),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о платежах в розничных продажах'
    )
    op.create_table('sales_taxes',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('sales_id', sa.Integer(), nullable=True, comment='Идентификатор операции'),
    sa.Column('type', sa.SmallInteger(), nullable=True, comment='Код виду податку/збору'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='Найменування виду податку/збору'),
    sa.Column('letter', sa.String(length=1), nullable=True, comment='Літерне позначення виду і ставки податку/збору'),
    sa.Column('prc', sa.Numeric(precision=15, scale=2), nullable=True, comment='Відсоток податку/збору'),
    sa.Column('sign', sa.Boolean(), nullable=True, comment='Ознака податку/збору, не включеного у вартість'),
    sa.Column('turnover', sa.Numeric(precision=15, scale=2), nullable=True, comment='Сума для розрахування податку/збору'),
    sa.Column('sum', sa.Numeric(precision=15, scale=2), nullable=True, comment='Сума податку/збору'),
    sa.ForeignKeyConstraint(['sales_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о налогах в розничных продажах'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_taxes')
    op.drop_table('sales_pays')
    op.drop_table('sales_check')
    op.drop_table('sales')
    # ### end Alembic commands ###
