"""empty message

Revision ID: 1a4cc0a120bf
Revises: 3fb3e7e10f16
Create Date: 2023-08-10 12:28:30.730104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4cc0a120bf'
down_revision = '3fb3e7e10f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('advances_doc_uid_idx', 'advances', ['doc_uid'], unique=False)
    op.create_index('incasses_doc_uid_idx', 'inkasses', ['doc_uid'], unique=False)
    op.create_index('podkreps_doc_uid_idx', 'podkreps', ['doc_uid'], unique=False)
    op.create_index('sales_doc_uid_idx', 'sales', ['doc_uid'], unique=False)
    op.create_index('shifts_doc_uid_idx', 'shifts', ['doc_uid'], unique=False)
    op.create_index('stornos_doc_uid_idx', 'stornos', ['doc_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('stornos_doc_uid_idx', table_name='stornos')
    op.drop_index('shifts_doc_uid_idx', table_name='shifts')
    op.drop_index('sales_doc_uid_idx', table_name='sales')
    op.drop_index('podkreps_doc_uid_idx', table_name='podkreps')
    op.drop_index('incasses_doc_uid_idx', table_name='inkasses')
    op.drop_index('advances_doc_uid_idx', table_name='advances')
    # ### end Alembic commands ###
