"""empty message

Revision ID: 24da89222823
Revises: 78cb7b4c9b58
Create Date: 2021-12-07 16:03:24.569592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24da89222823'
down_revision = '78cb7b4c9b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_keys', sa.Column('sign', sa.Boolean(), nullable=True, comment='Ключ для підпису'))
    op.add_column('department_keys', sa.Column('encrypt', sa.Boolean(), nullable=True, comment='Ключ для шифрування'))
    op.add_column('department_keys', sa.Column('key_tax_registered', sa.Boolean(), nullable=True, comment='Ключ зареєстрований у податковій'))
    op.alter_column('department_keys', 'taxform_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Лічильник відправки форм до податкової',
               existing_comment='Счетчик для отправки форм в налоговую',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department_keys', 'taxform_count',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Счетчик для отправки форм в налоговую',
               existing_comment='Лічильник відправки форм до податкової',
               existing_nullable=False)
    op.drop_column('department_keys', 'key_tax_registered')
    op.drop_column('department_keys', 'encrypt')
    op.drop_column('department_keys', 'sign')
    # ### end Alembic commands ###
