"""empty message

Revision ID: 30b858426d09
Revises: a6d47157d7bf
Create Date: 2022-11-23 15:59:12.606135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b858426d09'
down_revision = 'a6d47157d7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_keys', sa.Column('acsk', sa.String(length=100), nullable=True, comment='АЦСК'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_keys', 'acsk')
    # ### end Alembic commands ###
