"""empty message

Revision ID: 3b0671867f4f
Revises: 102d61566d9d
Create Date: 2021-12-21 19:42:58.860967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0671867f4f'
down_revision = '102d61566d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advances', sa.Column('testing', sa.Boolean(), nullable=True, comment='Ознака тестового нефіскального документа'))
    op.add_column('inkasses', sa.Column('testing', sa.Boolean(), nullable=True, comment='Ознака тестового нефіскального документа'))
    op.add_column('podkreps', sa.Column('testing', sa.Boolean(), nullable=True, comment='Ознака тестового нефіскального документа'))
    op.add_column('sales', sa.Column('testing', sa.Boolean(), nullable=True, comment='Ознака тестового нефіскального документа'))
    op.add_column('shifts', sa.Column('testing', sa.Boolean(), nullable=True, comment='Ознака тестового нефіскального документа'))
    op.add_column('z_reports', sa.Column('testing', sa.Boolean(), nullable=True, comment='Ознака тестового нефіскального документа'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('z_reports', 'testing')
    op.drop_column('shifts', 'testing')
    op.drop_column('sales', 'testing')
    op.drop_column('podkreps', 'testing')
    op.drop_column('inkasses', 'testing')
    op.drop_column('advances', 'testing')
    # ### end Alembic commands ###
