"""empty message

Revision ID: 3b968ff35ebd
Revises: 00531cee29ce
Create Date: 2021-04-14 15:39:28.765672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b968ff35ebd'
down_revision = '00531cee29ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('rro_id', sa.String(length=128), nullable=True, comment='Идентификатор РРО привязанного до отделения'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'rro_id')
    # ### end Alembic commands ###
