"""empty message

Revision ID: 3fb3e7e10f16
Revises: 90156dfe77d6
Create Date: 2023-07-10 17:18:06.452517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fb3e7e10f16'
down_revision = '90156dfe77d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advances', sa.Column('prev_hash', sa.String(length=64), nullable=True, comment='Хеш попереднього офлайн документа'))
    op.alter_column('advances', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Відділення',
               existing_comment='Отделение',
               existing_nullable=True)
    op.alter_column('advances', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Користувач',
               existing_comment='Пользователь',
               existing_nullable=True)
    op.alter_column('advances', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Час здійснення операції',
               existing_comment='Время совершения операции',
               existing_nullable=True)
    op.alter_column('advances', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Ідентифікатор зміни',
               existing_comment='Идентификатор смены',
               existing_nullable=True)
    op.alter_column('advances', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Час прийняття фіскальним сервером',
               existing_comment='Время принятия фискальным сервером (для пРРО)',
               existing_nullable=True)
    op.alter_column('advances', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Час відправки на фіскальний сервер',
               existing_comment='Время отправки на фискальный сервер (для пРРО)',
               existing_nullable=True)
    op.alter_column('advances', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальний номер чека',
               existing_comment='Локальный номер чека',
               existing_nullable=True)
    op.alter_column('advances', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека',
               existing_comment='Фискальный номер чека',
               existing_nullable=True)
    op.alter_column('advances', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст надісланого чека',
               existing_comment='Текстовое содержимое отправляемого чека',
               existing_nullable=True)
    op.alter_column('advances', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст чека як його бачить податкова',
               existing_comment='Текстовое содержимое чека как его видит налоговая',
               existing_nullable=True)
    op.alter_column('advances', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст відповіді податкової',
               existing_comment='Текстовое содержимое ответа налоговой',
               existing_nullable=True)
    op.alter_column('advances', 'storno_time',
               existing_type=mysql.DATETIME(),
               comment='Час сторно',
               existing_comment='Время сторно',
               existing_nullable=True)
    op.alter_column('advances', 'storno_tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека сторно',
               existing_comment='Фискальный номер чека сторно',
               existing_nullable=True)
    op.alter_column('advances', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.alter_column('advances', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фіскальний номер чека офлайн',
               existing_comment='Фискальный номер чека офлайн',
               existing_nullable=True)
    op.alter_column('advances', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.drop_column('advances', 'fiscal_error_code')
    op.drop_column('advances', 'fiscal_error_txt')
    op.add_column('inkasses', sa.Column('prev_hash', sa.String(length=64), nullable=True, comment='Хеш попереднього офлайн документа'))
    op.alter_column('inkasses', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Відділення',
               existing_comment='Отделение',
               existing_nullable=True)
    op.alter_column('inkasses', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Користувач',
               existing_comment='Пользователь',
               existing_nullable=True)
    op.alter_column('inkasses', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Час здійснення операції',
               existing_comment='Время совершения операции',
               existing_nullable=True)
    op.alter_column('inkasses', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Ідентифікатор зміни',
               existing_comment='Идентификатор смены',
               existing_nullable=True)
    op.alter_column('inkasses', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Час прийняття фіскальним сервером',
               existing_comment='Время принятия фискальным сервером (для пРРО)',
               existing_nullable=True)
    op.alter_column('inkasses', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Час відправки на фіскальний сервер',
               existing_comment='Время отправки на фискальный сервер (для пРРО)',
               existing_nullable=True)
    op.alter_column('inkasses', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальний номер чека',
               existing_comment='Локальный номер чека',
               existing_nullable=True)
    op.alter_column('inkasses', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека',
               existing_comment='Фискальный номер чека',
               existing_nullable=True)
    op.alter_column('inkasses', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст надісланого чека',
               existing_comment='Текстовое содержимое отправляемого чека',
               existing_nullable=True)
    op.alter_column('inkasses', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст чека як його бачить податкова',
               existing_comment='Текстовое содержимое чека как его видит налоговая',
               existing_nullable=True)
    op.alter_column('inkasses', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст відповіді податкової',
               existing_comment='Текстовое содержимое ответа налоговой',
               existing_nullable=True)
    op.alter_column('inkasses', 'storno_time',
               existing_type=mysql.DATETIME(),
               comment='Час сторно',
               existing_comment='Время сторно',
               existing_nullable=True)
    op.alter_column('inkasses', 'storno_tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека сторно',
               existing_comment='Фискальный номер чека сторно',
               existing_nullable=True)
    op.alter_column('inkasses', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.alter_column('inkasses', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фіскальний номер чека офлайн',
               existing_comment='Фискальный номер чека офлайн',
               existing_nullable=True)
    op.alter_column('inkasses', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.drop_column('inkasses', 'fiscal_error_code')
    op.drop_column('inkasses', 'fiscal_error_txt')
    op.alter_column('offline_checks', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Відділення',
               existing_comment='Отделение',
               existing_nullable=True)
    op.alter_column('offline_checks', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Користувач',
               existing_comment='Пользователь',
               existing_nullable=True)
    op.alter_column('offline_checks', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Час здійснення операції',
               existing_comment='Время совершения операции',
               existing_nullable=True)
    op.alter_column('offline_checks', 'operation_type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='Тип операції: 1 - відкриття офлайн, 0 - закриття офлайн',
               existing_comment='Тип операции: 1- открытие офлайн, 0 - закрытие офлайн',
               existing_nullable=False)
    op.alter_column('offline_checks', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Ідентифікатор зміни',
               existing_comment='Идентификатор смены',
               existing_nullable=True)
    op.alter_column('offline_checks', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Час прийняття фіскальним сервером',
               existing_comment='Время принятия фискальным сервером (для пРРО)',
               existing_nullable=True)
    op.alter_column('offline_checks', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Час відправки на фіскальний сервер',
               existing_comment='Время отправки на фискальный сервер (для пРРО)',
               existing_nullable=True)
    op.alter_column('offline_checks', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальний номер чека',
               existing_comment='Локальный номер чека',
               existing_nullable=True)
    op.alter_column('offline_checks', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст надісланого чека',
               existing_comment='Текстовое содержимое отправляемого чека',
               existing_nullable=True)
    op.alter_column('offline_checks', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст чека як його бачить податкова',
               existing_comment='Текстовое содержимое чека как его видит налоговая',
               existing_nullable=True)
    op.alter_column('offline_checks', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст відповіді податкової',
               existing_comment='Текстовое содержимое ответа налоговой',
               existing_nullable=True)
    op.alter_column('offline_checks', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.alter_column('offline_checks', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фіскальний номер чека офлайн',
               existing_comment='Фискальный номер чека офлайн',
               existing_nullable=True)
    op.create_table_comment(
        'offline_checks',
        ' Таблиця даних про чеки відкриття/закриття офлайн режиму ',
        existing_comment='Таблица данных о чеках открытия / закрытия офлайн режима',
        schema=None
    )
    op.drop_column('offline_checks', 'fiscal_error_code')
    op.drop_column('offline_checks', 'fiscal_error_txt')
    op.add_column('podkreps', sa.Column('prev_hash', sa.String(length=64), nullable=True, comment='Хеш попереднього офлайн документа'))
    op.alter_column('podkreps', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Відділення',
               existing_comment='Отделение',
               existing_nullable=True)
    op.alter_column('podkreps', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Користувач',
               existing_comment='Пользователь',
               existing_nullable=True)
    op.alter_column('podkreps', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Час здійснення операції',
               existing_comment='Время совершения операции',
               existing_nullable=True)
    op.alter_column('podkreps', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Ідентифікатор зміни',
               existing_comment='Идентификатор смены',
               existing_nullable=True)
    op.alter_column('podkreps', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Час прийняття фіскальним сервером',
               existing_comment='Время принятия фискальным сервером (для пРРО)',
               existing_nullable=True)
    op.alter_column('podkreps', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Час відправки на фіскальний сервер',
               existing_comment='Время отправки на фискальный сервер (для пРРО)',
               existing_nullable=True)
    op.alter_column('podkreps', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальний номер чека',
               existing_comment='Локальный номер чека',
               existing_nullable=True)
    op.alter_column('podkreps', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека',
               existing_comment='Фискальный номер чека',
               existing_nullable=True)
    op.alter_column('podkreps', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст надісланого чека',
               existing_comment='Текстовое содержимое отправляемого чека',
               existing_nullable=True)
    op.alter_column('podkreps', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст чека як його бачить податкова',
               existing_comment='Текстовое содержимое чека как его видит налоговая',
               existing_nullable=True)
    op.alter_column('podkreps', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст відповіді податкової',
               existing_comment='Текстовое содержимое ответа налоговой',
               existing_nullable=True)
    op.alter_column('podkreps', 'storno_time',
               existing_type=mysql.DATETIME(),
               comment='Час сторно',
               existing_comment='Время сторно',
               existing_nullable=True)
    op.alter_column('podkreps', 'storno_tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека сторно',
               existing_comment='Фискальный номер чека сторно',
               existing_nullable=True)
    op.alter_column('podkreps', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.alter_column('podkreps', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фіскальний номер чека офлайн',
               existing_comment='Фискальный номер чека офлайн',
               existing_nullable=True)
    op.alter_column('podkreps', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.drop_column('podkreps', 'fiscal_error_code')
    op.drop_column('podkreps', 'fiscal_error_txt')
    op.add_column('sales', sa.Column('prev_hash', sa.String(length=64), nullable=True, comment='Хеш попереднього офлайн документа'))
    op.alter_column('sales', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Відділення',
               existing_comment='Отделение',
               existing_nullable=True)
    op.alter_column('sales', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Користувач',
               existing_comment='Пользователь',
               existing_nullable=True)
    op.alter_column('sales', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Час здійснення операції',
               existing_comment='Время совершения операции',
               existing_nullable=True)
    op.alter_column('sales', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Ідентифікатор зміни',
               existing_comment='Идентификатор смены',
               existing_nullable=True)
    op.alter_column('sales', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Час прийняття фіскальним сервером',
               existing_comment='Время принятия фискальным сервером (для пРРО)',
               existing_nullable=True)
    op.alter_column('sales', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Час відправки на фіскальний сервер',
               existing_comment='Время отправки на фискальный сервер (для пРРО)',
               existing_nullable=True)
    op.alter_column('sales', 'orderretnum',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека возврата',
               existing_comment='Фискальный номер чека возврата',
               existing_nullable=True)
    op.alter_column('sales', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальний номер чека',
               existing_comment='Локальный номер чека',
               existing_nullable=True)
    op.alter_column('sales', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека',
               existing_comment='Фискальный номер чека',
               existing_nullable=True)
    op.alter_column('sales', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст надісланого чека',
               existing_comment='Текстовое содержимое отправляемого чека',
               existing_nullable=True)
    op.alter_column('sales', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст чека як його бачить податкова',
               existing_comment='Текстовое содержимое чека как его видит налоговая',
               existing_nullable=True)
    op.alter_column('sales', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст відповіді податкової',
               existing_comment='Текстовое содержимое ответа налоговой',
               existing_nullable=True)
    op.alter_column('sales', 'storno_time',
               existing_type=mysql.DATETIME(),
               comment='Час сторно',
               existing_comment='Время сторно',
               existing_nullable=True)
    op.alter_column('sales', 'storno_tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека сторно',
               existing_comment='Фискальный номер чека сторно',
               existing_nullable=True)
    op.alter_column('sales', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.alter_column('sales', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фіскальний номер чека офлайн',
               existing_comment='Фискальный номер чека офлайн',
               existing_nullable=True)
    op.alter_column('sales', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.drop_column('sales', 'fiscal_error_code')
    op.drop_column('sales', 'fiscal_error_txt')
    op.alter_column('shifts', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Відділення',
               existing_comment='Отделение',
               existing_nullable=True)
    op.alter_column('shifts', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Користувач',
               existing_comment='Пользователь',
               existing_nullable=True)
    op.alter_column('shifts', 'operation_type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='Тип операції: 1 - відкриття зміни, 0 - закриття зміни',
               existing_comment='Тип операции: 1- открытие смены, 0 - закрытие смены',
               existing_nullable=False)
    op.alter_column('shifts', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Час здійснення операції',
               existing_comment='Время совершения операции',
               existing_nullable=True)
    op.alter_column('shifts', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Час прийняття фіскальним сервером',
               existing_comment='Время принятия фискальным сервером (для пРРО)',
               existing_nullable=True)
    op.alter_column('shifts', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Час відправки на фіскальний сервер',
               existing_comment='Время отправки на фискальный сервер (для пРРО)',
               existing_nullable=True)
    op.alter_column('shifts', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальний номер чека',
               existing_comment='Локальный номер чека',
               existing_nullable=True)
    op.alter_column('shifts', 'fiscal_shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер зміни',
               existing_comment='Фискальный номер смены',
               existing_nullable=True)
    op.alter_column('shifts', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека',
               existing_comment='Фискальный номер чека',
               existing_nullable=True)
    op.alter_column('shifts', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст надісланого чека',
               existing_comment='Текстовое содержимое отправляемого чека',
               existing_nullable=True)
    op.alter_column('shifts', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст чека як його бачить податкова',
               existing_comment='Текстовое содержимое чека как его видит налоговая',
               existing_nullable=True)
    op.alter_column('shifts', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст відповіді податкової',
               existing_comment='Текстовое содержимое ответа налоговой',
               existing_nullable=True)
    op.alter_column('shifts', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='РРО  знаходиться в режимі офлайн',
               existing_comment='Отделение находится в режиме офлайн',
               existing_nullable=True)
    op.alter_column('shifts', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Ідентифікатор зміни',
               existing_comment='Идентификатор смены',
               existing_nullable=True)
    op.alter_column('shifts', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.alter_column('shifts', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фіскальний номер чека офлайн',
               existing_comment='Фискальный номер чека офлайн',
               existing_nullable=True)
    op.alter_column('shifts', 'prev_hash',
               existing_type=mysql.VARCHAR(length=64),
               comment='Хеш попереднього офлайн документа',
               existing_comment='Хэш предыдущего офлайн документа',
               existing_nullable=True)
    op.create_table_comment(
        'shifts',
        ' Таблиця даних про зміни ',
        existing_comment='Таблица данных о сменах',
        schema=None
    )
    op.drop_column('shifts', 'prro_localchecknumber')
    op.drop_column('shifts', 'prro_tn')
    op.drop_column('shifts', 'prro_offline_seed')
    op.drop_column('shifts', 'fiscal_error_code')
    op.drop_column('shifts', 'prro_ipn')
    op.drop_column('shifts', 'prro_zn')
    op.drop_column('shifts', 'prro_offline_session_id')
    op.drop_column('shifts', 'prro_address')
    op.drop_column('shifts', 'prro_offline_local_number')
    op.drop_column('shifts', 'prro_localnumber')
    op.drop_column('shifts', 'prro_department_name')
    op.drop_column('shifts', 'fiscal_error_txt')
    op.drop_column('shifts', 'prro_entity')
    op.drop_column('shifts', 'prro_org_name')
    op.add_column('stornos', sa.Column('prev_hash', sa.String(length=64), nullable=True, comment='Хеш попереднього офлайн документа'))
    op.alter_column('stornos', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Відділення',
               existing_comment='Отделение',
               existing_nullable=True)
    op.alter_column('stornos', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Користувач',
               existing_comment='Пользователь',
               existing_nullable=True)
    op.alter_column('stornos', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Час здійснення операції',
               existing_comment='Время совершения операции',
               existing_nullable=True)
    op.alter_column('stornos', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Ідентифікатор зміни',
               existing_comment='Идентификатор смены',
               existing_nullable=True)
    op.alter_column('stornos', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Час прийняття фіскальним сервером',
               existing_comment='Время принятия фискальным сервером (для пРРО)',
               existing_nullable=True)
    op.alter_column('stornos', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Час відправки на фіскальний сервер',
               existing_comment='Время отправки на фискальный сервер (для пРРО)',
               existing_nullable=True)
    op.alter_column('stornos', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальний номер чека',
               existing_comment='Локальный номер чека',
               existing_nullable=True)
    op.alter_column('stornos', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека',
               existing_comment='Фискальный номер чека',
               existing_nullable=True)
    op.alter_column('stornos', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст надісланого чека',
               existing_comment='Текстовое содержимое отправляемого чека',
               existing_nullable=True)
    op.alter_column('stornos', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст чека як його бачить податкова',
               existing_comment='Текстовое содержимое чека как его видит налоговая',
               existing_nullable=True)
    op.alter_column('stornos', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст відповіді податкової',
               existing_comment='Текстовое содержимое ответа налоговой',
               existing_nullable=True)
    op.alter_column('stornos', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.alter_column('stornos', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фіскальний номер чека офлайн',
               existing_comment='Фискальный номер чека офлайн',
               existing_nullable=True)
    op.alter_column('stornos', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.drop_column('stornos', 'fiscal_error_code')
    op.drop_column('stornos', 'fiscal_error_txt')
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               comment='Время когда Користувач был зарегистрирован',
               existing_comment='Время когда пользователь был зарегистрирован',
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               comment='Время когда Користувач заходил последний раз, используется для принудительной смены пароля',
               existing_comment='Время когда пользователь заходил последний раз, используется для принудительной смены пароля',
               existing_nullable=True)
    op.alter_column('z_reports', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Час здійснення операції',
               existing_comment='Время совершения операции',
               existing_nullable=True)
    op.alter_column('z_reports', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека',
               existing_comment='Фискальный номер чека',
               existing_nullable=True)
    op.alter_column('z_reports', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст надісланого чека',
               existing_comment='Текстовое содержимое отправляемого чека',
               existing_nullable=True)
    op.alter_column('z_reports', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст чека як його бачить податкова',
               existing_comment='Текстовое содержимое чека как его видит налоговая',
               existing_nullable=True)
    op.alter_column('z_reports', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Час відправки на фіскальний сервер',
               existing_comment='Время отправки на фискальный сервер (для пРРО)',
               existing_nullable=True)
    op.alter_column('z_reports', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фіскальний номер онлайн чека',
               existing_comment='Фискальный номер чека',
               existing_nullable=True)
    op.alter_column('z_reports', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовий вміст відповіді податкової',
               existing_comment='Текстовое содержимое ответа налоговой',
               existing_nullable=True)
    op.alter_column('z_reports', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Ідентифікатор зміни',
               existing_comment='Идентификатор смены',
               existing_nullable=True)
    op.alter_column('z_reports', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.alter_column('z_reports', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фіскальний номер чека офлайн',
               existing_comment='Фискальный номер чека офлайн',
               existing_nullable=True)
    op.alter_column('z_reports', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек збережено в режимі офлайн',
               existing_comment='Чек сохранен в режиме офлайн',
               existing_nullable=True)
    op.drop_column('z_reports', 'fiscal_error_code')
    op.drop_column('z_reports', 'fiscal_error_txt')
    op.drop_column('z_reports', 'printed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('z_reports', sa.Column('printed', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Напечатано, количество раз'))
    op.add_column('z_reports', sa.Column('fiscal_error_txt', mysql.MEDIUMTEXT(), nullable=True, comment='Текст ошибки'))
    op.add_column('z_reports', sa.Column('fiscal_error_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Код ошибки'))
    op.alter_column('z_reports', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('z_reports', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фискальный номер чека офлайн',
               existing_comment='Фіскальний номер чека офлайн',
               existing_nullable=True)
    op.alter_column('z_reports', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('z_reports', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Идентификатор смены',
               existing_comment='Ідентифікатор зміни',
               existing_nullable=True)
    op.alter_column('z_reports', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое ответа налоговой',
               existing_comment='Текстовий вміст відповіді податкової',
               existing_nullable=True)
    op.alter_column('z_reports', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека',
               existing_comment='Фіскальний номер онлайн чека',
               existing_nullable=True)
    op.alter_column('z_reports', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Время отправки на фискальный сервер (для пРРО)',
               existing_comment='Час відправки на фіскальний сервер',
               existing_nullable=True)
    op.alter_column('z_reports', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое чека как его видит налоговая',
               existing_comment='Текстовий вміст чека як його бачить податкова',
               existing_nullable=True)
    op.alter_column('z_reports', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое отправляемого чека',
               existing_comment='Текстовий вміст надісланого чека',
               existing_nullable=True)
    op.alter_column('z_reports', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека',
               existing_comment='Фіскальний номер онлайн чека',
               existing_nullable=True)
    op.alter_column('z_reports', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Время совершения операции',
               existing_comment='Час здійснення операції',
               existing_nullable=True)
    op.alter_column('users', 'last_login',
               existing_type=mysql.DATETIME(),
               comment='Время когда пользователь заходил последний раз, используется для принудительной смены пароля',
               existing_comment='Время когда Користувач заходил последний раз, используется для принудительной смены пароля',
               existing_nullable=True)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               comment='Время когда пользователь был зарегистрирован',
               existing_comment='Время когда Користувач был зарегистрирован',
               existing_nullable=True)
    op.add_column('stornos', sa.Column('fiscal_error_txt', mysql.MEDIUMTEXT(), nullable=True, comment='Текст ошибки'))
    op.add_column('stornos', sa.Column('fiscal_error_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Код ошибки'))
    op.alter_column('stornos', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('stornos', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фискальный номер чека офлайн',
               existing_comment='Фіскальний номер чека офлайн',
               existing_nullable=True)
    op.alter_column('stornos', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('stornos', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое ответа налоговой',
               existing_comment='Текстовий вміст відповіді податкової',
               existing_nullable=True)
    op.alter_column('stornos', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое чека как его видит налоговая',
               existing_comment='Текстовий вміст чека як його бачить податкова',
               existing_nullable=True)
    op.alter_column('stornos', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое отправляемого чека',
               existing_comment='Текстовий вміст надісланого чека',
               existing_nullable=True)
    op.alter_column('stornos', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека',
               existing_comment='Фіскальний номер онлайн чека',
               existing_nullable=True)
    op.alter_column('stornos', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальный номер чека',
               existing_comment='Локальний номер чека',
               existing_nullable=True)
    op.alter_column('stornos', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Время отправки на фискальный сервер (для пРРО)',
               existing_comment='Час відправки на фіскальний сервер',
               existing_nullable=True)
    op.alter_column('stornos', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Время принятия фискальным сервером (для пРРО)',
               existing_comment='Час прийняття фіскальним сервером',
               existing_nullable=True)
    op.alter_column('stornos', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Идентификатор смены',
               existing_comment='Ідентифікатор зміни',
               existing_nullable=True)
    op.alter_column('stornos', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Время совершения операции',
               existing_comment='Час здійснення операції',
               existing_nullable=True)
    op.alter_column('stornos', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Пользователь',
               existing_comment='Користувач',
               existing_nullable=True)
    op.alter_column('stornos', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Отделение',
               existing_comment='Відділення',
               existing_nullable=True)
    op.drop_column('stornos', 'prev_hash')
    op.add_column('shifts', sa.Column('prro_org_name', mysql.VARCHAR(length=256), nullable=True, comment='Найменування продавця (256 символів)'))
    op.add_column('shifts', sa.Column('prro_entity', mysql.VARCHAR(length=10), nullable=True, comment='Ідентифікатор запису ГО'))
    op.add_column('shifts', sa.Column('fiscal_error_txt', mysql.MEDIUMTEXT(), nullable=True, comment='Текст ошибки'))
    op.add_column('shifts', sa.Column('prro_department_name', mysql.VARCHAR(length=256), nullable=True, comment='Найменування точки продаж (256 символів)'))
    op.add_column('shifts', sa.Column('prro_localnumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Локальний номер документа'))
    op.add_column('shifts', sa.Column('prro_offline_local_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Локальний номер офлайн документа'))
    op.add_column('shifts', sa.Column('prro_address', mysql.VARCHAR(length=256), nullable=True, comment='Адреса точки продаж (256 символів)'))
    op.add_column('shifts', sa.Column('prro_offline_session_id', mysql.VARCHAR(length=128), nullable=True, comment='Ідентифікатор офлайн сесії'))
    op.add_column('shifts', sa.Column('prro_zn', mysql.VARCHAR(length=64), nullable=True, comment='Локальний номер реєстратора розрахункових операцій (64 символи)'))
    op.add_column('shifts', sa.Column('prro_ipn', mysql.VARCHAR(length=12), nullable=True, comment='Податковий номер або Індивідуальний номер платника ПДВ (12 символів)'))
    op.add_column('shifts', sa.Column('fiscal_error_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Код ошибки'))
    op.add_column('shifts', sa.Column('prro_offline_seed', mysql.VARCHAR(length=128), nullable=True, comment='Секретне число для обчислення фіскального номера офлайн документа'))
    op.add_column('shifts', sa.Column('prro_tn', mysql.VARCHAR(length=10), nullable=True, comment='ЄДРПОУ/ДРФО/№ паспорта продавця (10 символів)'))
    op.add_column('shifts', sa.Column('prro_localchecknumber', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Локальний номер документа'))
    op.create_table_comment(
        'shifts',
        'Таблица данных о сменах',
        existing_comment=' Таблиця даних про зміни ',
        schema=None
    )
    op.alter_column('shifts', 'prev_hash',
               existing_type=mysql.VARCHAR(length=64),
               comment='Хэш предыдущего офлайн документа',
               existing_comment='Хеш попереднього офлайн документа',
               existing_nullable=True)
    op.alter_column('shifts', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фискальный номер чека офлайн',
               existing_comment='Фіскальний номер чека офлайн',
               existing_nullable=True)
    op.alter_column('shifts', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('shifts', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Идентификатор смены',
               existing_comment='Ідентифікатор зміни',
               existing_nullable=True)
    op.alter_column('shifts', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Отделение находится в режиме офлайн',
               existing_comment='РРО  знаходиться в режимі офлайн',
               existing_nullable=True)
    op.alter_column('shifts', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое ответа налоговой',
               existing_comment='Текстовий вміст відповіді податкової',
               existing_nullable=True)
    op.alter_column('shifts', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое чека как его видит налоговая',
               existing_comment='Текстовий вміст чека як його бачить податкова',
               existing_nullable=True)
    op.alter_column('shifts', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое отправляемого чека',
               existing_comment='Текстовий вміст надісланого чека',
               existing_nullable=True)
    op.alter_column('shifts', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека',
               existing_comment='Фіскальний номер онлайн чека',
               existing_nullable=True)
    op.alter_column('shifts', 'fiscal_shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер смены',
               existing_comment='Фіскальний номер зміни',
               existing_nullable=True)
    op.alter_column('shifts', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальный номер чека',
               existing_comment='Локальний номер чека',
               existing_nullable=True)
    op.alter_column('shifts', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Время отправки на фискальный сервер (для пРРО)',
               existing_comment='Час відправки на фіскальний сервер',
               existing_nullable=True)
    op.alter_column('shifts', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Время принятия фискальным сервером (для пРРО)',
               existing_comment='Час прийняття фіскальним сервером',
               existing_nullable=True)
    op.alter_column('shifts', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Время совершения операции',
               existing_comment='Час здійснення операції',
               existing_nullable=True)
    op.alter_column('shifts', 'operation_type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='Тип операции: 1- открытие смены, 0 - закрытие смены',
               existing_comment='Тип операції: 1 - відкриття зміни, 0 - закриття зміни',
               existing_nullable=False)
    op.alter_column('shifts', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Пользователь',
               existing_comment='Користувач',
               existing_nullable=True)
    op.alter_column('shifts', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Отделение',
               existing_comment='Відділення',
               existing_nullable=True)
    op.add_column('sales', sa.Column('fiscal_error_txt', mysql.MEDIUMTEXT(), nullable=True, comment='Текст ошибки'))
    op.add_column('sales', sa.Column('fiscal_error_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Код ошибки'))
    op.alter_column('sales', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('sales', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фискальный номер чека офлайн',
               existing_comment='Фіскальний номер чека офлайн',
               existing_nullable=True)
    op.alter_column('sales', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('sales', 'storno_tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека сторно',
               existing_comment='Фіскальний номер онлайн чека сторно',
               existing_nullable=True)
    op.alter_column('sales', 'storno_time',
               existing_type=mysql.DATETIME(),
               comment='Время сторно',
               existing_comment='Час сторно',
               existing_nullable=True)
    op.alter_column('sales', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое ответа налоговой',
               existing_comment='Текстовий вміст відповіді податкової',
               existing_nullable=True)
    op.alter_column('sales', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое чека как его видит налоговая',
               existing_comment='Текстовий вміст чека як його бачить податкова',
               existing_nullable=True)
    op.alter_column('sales', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое отправляемого чека',
               existing_comment='Текстовий вміст надісланого чека',
               existing_nullable=True)
    op.alter_column('sales', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека',
               existing_comment='Фіскальний номер онлайн чека',
               existing_nullable=True)
    op.alter_column('sales', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальный номер чека',
               existing_comment='Локальний номер чека',
               existing_nullable=True)
    op.alter_column('sales', 'orderretnum',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека возврата',
               existing_comment='Фіскальний номер онлайн чека возврата',
               existing_nullable=True)
    op.alter_column('sales', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Время отправки на фискальный сервер (для пРРО)',
               existing_comment='Час відправки на фіскальний сервер',
               existing_nullable=True)
    op.alter_column('sales', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Время принятия фискальным сервером (для пРРО)',
               existing_comment='Час прийняття фіскальним сервером',
               existing_nullable=True)
    op.alter_column('sales', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Идентификатор смены',
               existing_comment='Ідентифікатор зміни',
               existing_nullable=True)
    op.alter_column('sales', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Время совершения операции',
               existing_comment='Час здійснення операції',
               existing_nullable=True)
    op.alter_column('sales', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Пользователь',
               existing_comment='Користувач',
               existing_nullable=True)
    op.alter_column('sales', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Отделение',
               existing_comment='Відділення',
               existing_nullable=True)
    op.drop_column('sales', 'prev_hash')
    op.add_column('podkreps', sa.Column('fiscal_error_txt', mysql.MEDIUMTEXT(), nullable=True, comment='Текст ошибки'))
    op.add_column('podkreps', sa.Column('fiscal_error_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Код ошибки'))
    op.alter_column('podkreps', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('podkreps', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фискальный номер чека офлайн',
               existing_comment='Фіскальний номер чека офлайн',
               existing_nullable=True)
    op.alter_column('podkreps', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('podkreps', 'storno_tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека сторно',
               existing_comment='Фіскальний номер онлайн чека сторно',
               existing_nullable=True)
    op.alter_column('podkreps', 'storno_time',
               existing_type=mysql.DATETIME(),
               comment='Время сторно',
               existing_comment='Час сторно',
               existing_nullable=True)
    op.alter_column('podkreps', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое ответа налоговой',
               existing_comment='Текстовий вміст відповіді податкової',
               existing_nullable=True)
    op.alter_column('podkreps', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое чека как его видит налоговая',
               existing_comment='Текстовий вміст чека як його бачить податкова',
               existing_nullable=True)
    op.alter_column('podkreps', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое отправляемого чека',
               existing_comment='Текстовий вміст надісланого чека',
               existing_nullable=True)
    op.alter_column('podkreps', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека',
               existing_comment='Фіскальний номер онлайн чека',
               existing_nullable=True)
    op.alter_column('podkreps', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальный номер чека',
               existing_comment='Локальний номер чека',
               existing_nullable=True)
    op.alter_column('podkreps', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Время отправки на фискальный сервер (для пРРО)',
               existing_comment='Час відправки на фіскальний сервер',
               existing_nullable=True)
    op.alter_column('podkreps', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Время принятия фискальным сервером (для пРРО)',
               existing_comment='Час прийняття фіскальним сервером',
               existing_nullable=True)
    op.alter_column('podkreps', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Идентификатор смены',
               existing_comment='Ідентифікатор зміни',
               existing_nullable=True)
    op.alter_column('podkreps', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Время совершения операции',
               existing_comment='Час здійснення операції',
               existing_nullable=True)
    op.alter_column('podkreps', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Пользователь',
               existing_comment='Користувач',
               existing_nullable=True)
    op.alter_column('podkreps', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Отделение',
               existing_comment='Відділення',
               existing_nullable=True)
    op.drop_column('podkreps', 'prev_hash')
    op.add_column('offline_checks', sa.Column('fiscal_error_txt', mysql.MEDIUMTEXT(), nullable=True, comment='Текст ошибки'))
    op.add_column('offline_checks', sa.Column('fiscal_error_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Код ошибки'))
    op.create_table_comment(
        'offline_checks',
        'Таблица данных о чеках открытия / закрытия офлайн режима',
        existing_comment=' Таблиця даних про чеки відкриття/закриття офлайн режиму ',
        schema=None
    )
    op.alter_column('offline_checks', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фискальный номер чека офлайн',
               existing_comment='Фіскальний номер чека офлайн',
               existing_nullable=True)
    op.alter_column('offline_checks', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('offline_checks', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое ответа налоговой',
               existing_comment='Текстовий вміст відповіді податкової',
               existing_nullable=True)
    op.alter_column('offline_checks', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое чека как его видит налоговая',
               existing_comment='Текстовий вміст чека як його бачить податкова',
               existing_nullable=True)
    op.alter_column('offline_checks', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое отправляемого чека',
               existing_comment='Текстовий вміст надісланого чека',
               existing_nullable=True)
    op.alter_column('offline_checks', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальный номер чека',
               existing_comment='Локальний номер чека',
               existing_nullable=True)
    op.alter_column('offline_checks', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Время отправки на фискальный сервер (для пРРО)',
               existing_comment='Час відправки на фіскальний сервер',
               existing_nullable=True)
    op.alter_column('offline_checks', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Время принятия фискальным сервером (для пРРО)',
               existing_comment='Час прийняття фіскальним сервером',
               existing_nullable=True)
    op.alter_column('offline_checks', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Идентификатор смены',
               existing_comment='Ідентифікатор зміни',
               existing_nullable=True)
    op.alter_column('offline_checks', 'operation_type',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='Тип операции: 1- открытие офлайн, 0 - закрытие офлайн',
               existing_comment='Тип операції: 1 - відкриття офлайн, 0 - закриття офлайн',
               existing_nullable=False)
    op.alter_column('offline_checks', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Время совершения операции',
               existing_comment='Час здійснення операції',
               existing_nullable=True)
    op.alter_column('offline_checks', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Пользователь',
               existing_comment='Користувач',
               existing_nullable=True)
    op.alter_column('offline_checks', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Отделение',
               existing_comment='Відділення',
               existing_nullable=True)
    op.add_column('inkasses', sa.Column('fiscal_error_txt', mysql.MEDIUMTEXT(), nullable=True, comment='Текст ошибки'))
    op.add_column('inkasses', sa.Column('fiscal_error_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Код ошибки'))
    op.alter_column('inkasses', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('inkasses', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фискальный номер чека офлайн',
               existing_comment='Фіскальний номер чека офлайн',
               existing_nullable=True)
    op.alter_column('inkasses', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('inkasses', 'storno_tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека сторно',
               existing_comment='Фіскальний номер онлайн чека сторно',
               existing_nullable=True)
    op.alter_column('inkasses', 'storno_time',
               existing_type=mysql.DATETIME(),
               comment='Время сторно',
               existing_comment='Час сторно',
               existing_nullable=True)
    op.alter_column('inkasses', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое ответа налоговой',
               existing_comment='Текстовий вміст відповіді податкової',
               existing_nullable=True)
    op.alter_column('inkasses', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое чека как его видит налоговая',
               existing_comment='Текстовий вміст чека як його бачить податкова',
               existing_nullable=True)
    op.alter_column('inkasses', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое отправляемого чека',
               existing_comment='Текстовий вміст надісланого чека',
               existing_nullable=True)
    op.alter_column('inkasses', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека',
               existing_comment='Фіскальний номер онлайн чека',
               existing_nullable=True)
    op.alter_column('inkasses', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальный номер чека',
               existing_comment='Локальний номер чека',
               existing_nullable=True)
    op.alter_column('inkasses', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Время отправки на фискальный сервер (для пРРО)',
               existing_comment='Час відправки на фіскальний сервер',
               existing_nullable=True)
    op.alter_column('inkasses', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Время принятия фискальным сервером (для пРРО)',
               existing_comment='Час прийняття фіскальним сервером',
               existing_nullable=True)
    op.alter_column('inkasses', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Идентификатор смены',
               existing_comment='Ідентифікатор зміни',
               existing_nullable=True)
    op.alter_column('inkasses', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Время совершения операции',
               existing_comment='Час здійснення операції',
               existing_nullable=True)
    op.alter_column('inkasses', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Пользователь',
               existing_comment='Користувач',
               existing_nullable=True)
    op.alter_column('inkasses', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Отделение',
               existing_comment='Відділення',
               existing_nullable=True)
    op.drop_column('inkasses', 'prev_hash')
    op.add_column('advances', sa.Column('fiscal_error_txt', mysql.MEDIUMTEXT(), nullable=True, comment='Текст ошибки'))
    op.add_column('advances', sa.Column('fiscal_error_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='Код ошибки'))
    op.alter_column('advances', 'offline',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('advances', 'offline_tax_id',
               existing_type=mysql.VARCHAR(length=32),
               comment='Фискальный номер чека офлайн',
               existing_comment='Фіскальний номер чека офлайн',
               existing_nullable=True)
    op.alter_column('advances', 'offline_check',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Чек сохранен в режиме офлайн',
               existing_comment='Чек збережено в режимі офлайн',
               existing_nullable=True)
    op.alter_column('advances', 'storno_tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека сторно',
               existing_comment='Фіскальний номер онлайн чека сторно',
               existing_nullable=True)
    op.alter_column('advances', 'storno_time',
               existing_type=mysql.DATETIME(),
               comment='Время сторно',
               existing_comment='Час сторно',
               existing_nullable=True)
    op.alter_column('advances', 'fiscal_ticket',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое ответа налоговой',
               existing_comment='Текстовий вміст відповіді податкової',
               existing_nullable=True)
    op.alter_column('advances', 'fiscal_xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое чека как его видит налоговая',
               existing_comment='Текстовий вміст чека як його бачить податкова',
               existing_nullable=True)
    op.alter_column('advances', 'xml',
               existing_type=mysql.MEDIUMTEXT(),
               comment='Текстовое содержимое отправляемого чека',
               existing_comment='Текстовий вміст надісланого чека',
               existing_nullable=True)
    op.alter_column('advances', 'tax_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Фискальный номер чека',
               existing_comment='Фіскальний номер онлайн чека',
               existing_nullable=True)
    op.alter_column('advances', 'pid',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Локальный номер чека',
               existing_comment='Локальний номер чека',
               existing_nullable=True)
    op.alter_column('advances', 'server_time',
               existing_type=mysql.DATETIME(),
               comment='Время отправки на фискальный сервер (для пРРО)',
               existing_comment='Час відправки на фіскальний сервер',
               existing_nullable=True)
    op.alter_column('advances', 'fiscal_time',
               existing_type=mysql.DATETIME(),
               comment='Время принятия фискальным сервером (для пРРО)',
               existing_comment='Час прийняття фіскальним сервером',
               existing_nullable=True)
    op.alter_column('advances', 'shift_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Идентификатор смены',
               existing_comment='Ідентифікатор зміни',
               existing_nullable=True)
    op.alter_column('advances', 'operation_time',
               existing_type=mysql.DATETIME(),
               comment='Время совершения операции',
               existing_comment='Час здійснення операції',
               existing_nullable=True)
    op.alter_column('advances', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Пользователь',
               existing_comment='Користувач',
               existing_nullable=True)
    op.alter_column('advances', 'department_id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='Отделение',
               existing_comment='Відділення',
               existing_nullable=True)
    op.drop_column('advances', 'prev_hash')
    # ### end Alembic commands ###
