"""empty message

Revision ID: 456eec135b5a
Revises: 0ad60b4a68f3
Create Date: 2023-06-01 16:11:56.557388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '456eec135b5a'
down_revision = '0ad60b4a68f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('offline_status', sa.SmallInteger(), nullable=False, comment='Перейшли в режим офлайн'))
    op.alter_column('departments', 'offline',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='Режим офлайн вкл/викл',
               existing_comment='Режим офлайн',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'offline',
               existing_type=mysql.SMALLINT(display_width=6),
               comment='Режим офлайн',
               existing_comment='Режим офлайн вкл/викл',
               existing_nullable=False)
    op.drop_column('departments', 'offline_status')
    # ### end Alembic commands ###
