"""empty message

Revision ID: 48b210411f63
Revises: 54d65babef1f
Create Date: 2021-12-22 23:37:36.054313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b210411f63'
down_revision = '54d65babef1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('prro_offline_local_number', sa.Integer(), nullable=True, comment='Локальний номер оффлайн документа'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'prro_offline_local_number')
    # ### end Alembic commands ###
