"""empty message

Revision ID: 4a2d38893f17
Revises: a0135f46b575
Create Date: 2021-12-23 00:10:03.843687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2d38893f17'
down_revision = 'a0135f46b575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advances', sa.Column('offline', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('inkasses', sa.Column('offline', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('podkreps', sa.Column('offline', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('sales', sa.Column('offline', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('z_reports', sa.Column('offline', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('z_reports', 'offline')
    op.drop_column('sales', 'offline')
    op.drop_column('podkreps', 'offline')
    op.drop_column('inkasses', 'offline')
    op.drop_column('advances', 'offline')
    # ### end Alembic commands ###
