"""empty message

Revision ID: 54d65babef1f
Revises: bdb95357d917
Create Date: 2021-12-22 16:55:14.593684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d65babef1f'
down_revision = 'bdb95357d917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offline_checks',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Отделение'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Пользователь'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='Время совершения операции'),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False, comment='Тип операции: 1- открытие оффлайн, 0 - закрытие оффлайн'),
    sa.Column('shift_id', sa.Integer(), nullable=True, comment='Идентификатор смены'),
    sa.Column('fiscal_time', sa.DateTime(), nullable=True, comment='Время принятия фискальным сервером (для пРРО)'),
    sa.Column('server_time', sa.DateTime(), nullable=True, comment='Время отправки на фискальный сервер (для пРРО)'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='Локальный номер чека'),
    sa.Column('xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое отправляемого чека'),
    sa.Column('fiscal_xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое чека как его видит налоговая'),
    sa.Column('fiscal_ticket', sa.TEXT(), nullable=True, comment='Текстовое содержимое ответа налоговой'),
    sa.Column('fiscal_error_code', sa.Integer(), nullable=True, comment='Код ошибки'),
    sa.Column('fiscal_error_txt', sa.TEXT(), nullable=True, comment='Текст ошибки'),
    sa.Column('testing', sa.Boolean(), nullable=True, comment='Ознака тестового нефіскального документа'),
    sa.Column('offline_fiscal_xml_signed', sa.LargeBinary(), nullable=True, comment='Вміст файлу XML з сертифікатом підпису'),
    sa.Column('offline_check', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'),
    sa.Column('offline_tax_id', sa.String(length=32), nullable=True, comment='Фискальный номер чека оффлайн'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о чеках открытия / закрытия оффлайн режима'
    )
    op.add_column('advances', sa.Column('offline_fiscal_xml_signed', sa.LargeBinary(), nullable=True, comment='Вміст файлу XML з сертифікатом підпису'))
    op.add_column('advances', sa.Column('offline_check', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('advances', sa.Column('offline_tax_id', sa.String(length=32), nullable=True, comment='Фискальный номер чека оффлайн'))
    op.add_column('inkasses', sa.Column('offline_fiscal_xml_signed', sa.LargeBinary(), nullable=True, comment='Вміст файлу XML з сертифікатом підпису'))
    op.add_column('inkasses', sa.Column('offline_check', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('inkasses', sa.Column('offline_tax_id', sa.String(length=32), nullable=True, comment='Фискальный номер чека оффлайн'))
    op.add_column('podkreps', sa.Column('offline_fiscal_xml_signed', sa.LargeBinary(), nullable=True, comment='Вміст файлу XML з сертифікатом підпису'))
    op.add_column('podkreps', sa.Column('offline_check', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('podkreps', sa.Column('offline_tax_id', sa.String(length=32), nullable=True, comment='Фискальный номер чека оффлайн'))
    op.add_column('sales', sa.Column('offline_fiscal_xml_signed', sa.LargeBinary(), nullable=True, comment='Вміст файлу XML з сертифікатом підпису'))
    op.add_column('sales', sa.Column('offline_check', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('sales', sa.Column('offline_tax_id', sa.String(length=32), nullable=True, comment='Фискальный номер чека оффлайн'))
    op.add_column('shifts', sa.Column('offline_fiscal_xml_signed', sa.LargeBinary(), nullable=True, comment='Вміст файлу XML з сертифікатом підпису'))
    op.add_column('shifts', sa.Column('offline_check', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('shifts', sa.Column('offline_tax_id', sa.String(length=32), nullable=True, comment='Фискальный номер чека оффлайн'))
    op.add_column('z_reports', sa.Column('offline_fiscal_xml_signed', sa.LargeBinary(), nullable=True, comment='Вміст файлу XML з сертифікатом підпису'))
    op.add_column('z_reports', sa.Column('offline_check', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'))
    op.add_column('z_reports', sa.Column('offline_tax_id', sa.String(length=32), nullable=True, comment='Фискальный номер чека оффлайн'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('z_reports', 'offline_tax_id')
    op.drop_column('z_reports', 'offline_check')
    op.drop_column('z_reports', 'offline_fiscal_xml_signed')
    op.drop_column('shifts', 'offline_tax_id')
    op.drop_column('shifts', 'offline_check')
    op.drop_column('shifts', 'offline_fiscal_xml_signed')
    op.drop_column('sales', 'offline_tax_id')
    op.drop_column('sales', 'offline_check')
    op.drop_column('sales', 'offline_fiscal_xml_signed')
    op.drop_column('podkreps', 'offline_tax_id')
    op.drop_column('podkreps', 'offline_check')
    op.drop_column('podkreps', 'offline_fiscal_xml_signed')
    op.drop_column('inkasses', 'offline_tax_id')
    op.drop_column('inkasses', 'offline_check')
    op.drop_column('inkasses', 'offline_fiscal_xml_signed')
    op.drop_column('advances', 'offline_tax_id')
    op.drop_column('advances', 'offline_check')
    op.drop_column('advances', 'offline_fiscal_xml_signed')
    op.drop_table('offline_checks')
    # ### end Alembic commands ###
