"""empty message

Revision ID: 564bc80f0581
Revises: 38772c4f82c1
Create Date: 2021-12-02 12:07:02.049639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '564bc80f0581'
down_revision = '38772c4f82c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_keys', sa.Column('edrpou', sa.String(length=16), nullable=True, comment='EDRPOU'))
    op.drop_constraint('department_keys_ibfk_1', 'department_keys', type_='foreignkey')
    op.drop_column('department_keys', 'department_id')
    op.create_foreign_key(None, 'departments', 'department_keys', ['prro_key_id'], ['id'])
    op.create_foreign_key(None, 'departments', 'department_keys', ['taxform_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.add_column('department_keys', sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='Отделение'))
    op.create_foreign_key('department_keys_ibfk_1', 'department_keys', 'departments', ['department_id'], ['id'])
    op.drop_column('department_keys', 'edrpou')
    # ### end Alembic commands ###
