"""empty message

Revision ID: 5f0144727371
Revises: 
Create Date: 2021-04-14 14:27:34.020964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0144727371'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_keys',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Назва'),
    sa.Column('public_key', sa.String(length=100), nullable=True, comment='Ідентифікатор відкритого ключа'),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('key_password', sa.String(length=100), nullable=False, comment='Пароль захисту ключа'),
    sa.Column('begin_time', sa.DateTime(), nullable=True, comment='Время выдачи ключа'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='Время окончания ключа'),
    sa.Column('key_data', sa.Binary(), nullable=True, comment='Содержимое файла ключа'),
    sa.Column('key_data_txt', sa.JSON(), nullable=True, comment='Текстовое содержимое файла ключа'),
    sa.Column('cert1_data', sa.Binary(), nullable=True, comment='Содержимое файла 1 сертификата'),
    sa.Column('cert2_data', sa.Binary(), nullable=True, comment='Содержимое файла 2 сертификата'),
    sa.Column('key_content', sa.String(length=4096), nullable=True, comment='Распакованное содержимое криптоключа'),
    sa.Column('box_id', sa.String(length=100), nullable=True, comment='Идентификатор крипто-сессии'),
    sa.Column('key_role', sa.String(length=10), nullable=True, comment='Роль ключа'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник ключей ЭЦП компаний'
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('address', sa.String(length=300), nullable=True, comment='Адрес отделения'),
    sa.Column('full_name', sa.Text(), nullable=True, comment='Полное наименование отделения'),
    sa.PrimaryKeyConstraint('id'),
    comment=' Таблица содержащая информацию о текущих подразделениях компании '
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='Название права'),
    sa.PrimaryKeyConstraint('id'),
    comment=' Таблица названий различных прав для отдельных ролей '
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('name', sa.String(length=64), nullable=True, comment='Название роли'),
    sa.PrimaryKeyConstraint('id'),
    comment=' Таблица ролей пользователей для разных уровней доступа до функционала программы '
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('created', sa.DateTime(), nullable=True, comment='Время когда пользователь был зарегистрирован'),
    sa.Column('last_login', sa.DateTime(), nullable=True, comment='Время когда пользователь заходил последний раз, используется для принудительной смены пароля'),
    sa.Column('deactivated', sa.DateTime(), nullable=True, comment='Время когда пользователя деактивировали'),
    sa.Column('login', sa.String(length=32), nullable=True, comment='Логин пользователя для авторизации при входе в систему'),
    sa.Column('password_hash', sa.String(length=512), nullable=True, comment='Хэш пороля доступа в SHA-512'),
    sa.PrimaryKeyConstraint('id'),
    comment=' Таблица пользователей программного продукта '
    )
    op.create_table('department_keys',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('department_id', sa.Integer(), nullable=False, comment='Отделение'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='Назва'),
    sa.Column('public_key', sa.String(length=100), nullable=True, comment='Ідентифікатор відкритого ключа'),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('key_password', sa.String(length=100), nullable=False, comment='Пароль захисту ключа'),
    sa.Column('begin_time', sa.DateTime(), nullable=True, comment='Время выдачи ключа'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='Время окончания ключа'),
    sa.Column('key_data', sa.Binary(), nullable=True, comment='Содержимое файла ключа'),
    sa.Column('key_data_txt', sa.JSON(), nullable=True, comment='Текстовое содержимое файла ключа'),
    sa.Column('cert1_data', sa.Binary(), nullable=True, comment='Содержимое файла 1 сертификата'),
    sa.Column('cert2_data', sa.Binary(), nullable=True, comment='Содержимое файла 2 сертификата'),
    sa.Column('key_content', sa.String(length=4096), nullable=True, comment='Распакованное содержимое криптоключа'),
    sa.Column('box_id', sa.String(length=100), nullable=True, comment='Идентификатор крипто-сессии'),
    sa.Column('key_role', sa.String(length=10), nullable=True, comment='Роль ключа'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник ключей ЭЦП подразделений'
    )
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Отделение'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Пользователь'),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False, comment='Тип операции: 1- открытие смены, 0 - закрытие смены'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='Время совершения операции'),
    sa.Column('fiscal_time', sa.DateTime(), nullable=True, comment='Время принятия фискальным сервером (для пРРО)'),
    sa.Column('server_time', sa.DateTime(), nullable=True, comment='Время отправки на фискальный сервер (для пРРО)'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='Локальный номер чека'),
    sa.Column('fiscal_shift_id', sa.Integer(), nullable=True, comment='Фискальный номер смены'),
    sa.Column('tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека'),
    sa.Column('xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое отправляемого чека'),
    sa.Column('fiscal_xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое чека как его видит налоговая'),
    sa.Column('fiscal_ticket', sa.TEXT(), nullable=True, comment='Текстовое содержимое ответа налоговой'),
    sa.Column('fiscal_error_code', sa.Integer(), nullable=True, comment='Код ошибки'),
    sa.Column('fiscal_error_txt', sa.TEXT(), nullable=True, comment='Текст ошибки'),
    sa.Column('prro_org_name', sa.String(length=256), nullable=True, comment='Найменування продавця (256 символів)'),
    sa.Column('prro_department_name', sa.String(length=256), nullable=True, comment='Найменування точки продаж (256 символів)'),
    sa.Column('prro_address', sa.String(length=256), nullable=True, comment='Адреса точки продаж (256 символів)'),
    sa.Column('prro_tn', sa.String(length=10), nullable=True, comment='ЄДРПОУ/ДРФО/№ паспорта продавця (10 символів)'),
    sa.Column('prro_ipn', sa.String(length=12), nullable=True, comment='Податковий номер або Індивідуальний номер платника ПДВ (12 символів)'),
    sa.Column('prro_entity', sa.String(length=10), nullable=True, comment='Ідентифікатор запису ГО'),
    sa.Column('prro_zn', sa.String(length=64), nullable=True, comment='Локальний номер реєстратора розрахункових операцій (64 символи)'),
    sa.Column('prro_localnumber', sa.Integer(), nullable=True, comment='Локальний номер документа'),
    sa.Column('prro_localchecknumber', sa.Integer(), nullable=True, comment='Локальний номер документа'),
    sa.Column('prro_offline_session_id', sa.String(length=128), nullable=True, comment='Ідентифікатор офлайн сесії'),
    sa.Column('prro_offline_seed', sa.String(length=128), nullable=True, comment='Секретне число для обчислення фіскального номера офлайн документа'),
    sa.Column('offline', sa.Boolean(), nullable=True, comment='Отделение находится в режиме оффлайн'),
    sa.Column('p_offline', sa.Boolean(), nullable=True, comment='Отделение находится в режиме эмуляции оффлайн'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о сменах'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shifts')
    op.drop_table('department_keys')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permission')
    op.drop_table('departments')
    op.drop_table('company_keys')
    # ### end Alembic commands ###
