"""empty message

Revision ID: 661bbd8d248b
Revises: 7b1cf4ec31d6
Create Date: 2022-09-10 09:48:17.065447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '661bbd8d248b'
down_revision = '7b1cf4ec31d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_keys', sa.Column('key_role_tax_form', sa.String(length=10), nullable=True, comment='Роль ключа для підписання податкових форм'))
    op.alter_column('departments', 'prro_name',
               existing_type=mysql.VARCHAR(length=256),
               comment='Найменування ПРРО (256 символів)',
               existing_comment='Найменування РРО (256 символів)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'prro_name',
               existing_type=mysql.VARCHAR(length=256),
               comment='Найменування РРО (256 символів)',
               existing_comment='Найменування ПРРО (256 символів)',
               existing_nullable=True)
    op.drop_column('department_keys', 'key_role_tax_form')
    # ### end Alembic commands ###
