"""empty message

Revision ID: 6f330981535d
Revises: 30b858426d09
Create Date: 2022-12-15 19:52:27.184279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f330981535d'
down_revision = '30b858426d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'p_offline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('p_offline', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Отделение находится в режиме эмуляции офлайн'))
    # ### end Alembic commands ###
