"""empty message

Revision ID: 703ab5641806
Revises: 564bc80f0581
Create Date: 2021-12-02 14:06:05.345104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703ab5641806'
down_revision = '564bc80f0581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_keys', sa.Column('taxform_count', sa.Integer(), nullable=False, comment='Счетчик для отправки форм в налоговую'))
    op.add_column('department_keys', sa.Column('ceo_fio', sa.String(length=128), nullable=True, comment='ПІБ директора'))
    op.add_column('department_keys', sa.Column('ceo_tin', sa.String(length=16), nullable=True, comment='РНОКПП'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_keys', 'ceo_tin')
    op.drop_column('department_keys', 'ceo_fio')
    op.drop_column('department_keys', 'taxform_count')
    # ### end Alembic commands ###
