"""empty message

Revision ID: 78cb7b4c9b58
Revises: 703ab5641806
Create Date: 2021-12-02 15:56:43.275818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cb7b4c9b58'
down_revision = '703ab5641806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_keys', sa.Column('signer_type', sa.String(length=20), nullable=True, comment='Тип підпису: Касир / Старший касир / Припинення роботи'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_keys', 'signer_type')
    # ### end Alembic commands ###
