"""empty message

Revision ID: 823ec310205f
Revises: 121d9a36cbd6
Create Date: 2022-09-05 18:34:49.798716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '823ec310205f'
down_revision = '121d9a36cbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department_keys', 'key_password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='Пароль захисту ключа')
    op.add_column('departments', sa.Column('offline', sa.SMALLINT, nullable=False, comment='Режим офлайн'))
    op.create_table_comment(
        'sales',
        'Таблица данных о розничных продажах',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'sales',
        existing_comment='Таблица данных о розничных продажах',
        schema=None
    )
    op.drop_column('departments', 'offline')
    op.alter_column('department_keys', 'key_password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='Пароль захисту ключа')
    # ### end Alembic commands ###
