"""empty message

Revision ID: 890514fd1771
Revises: 8de791403d24
Create Date: 2023-10-05 21:09:55.993470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890514fd1771'
down_revision = '8de791403d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offline_checks', sa.Column('last_fiscal_error_txt', sa.String(length=128), nullable=True, comment='Причина переходу в офлайн'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offline_checks', 'last_fiscal_error_txt')
    # ### end Alembic commands ###
