"""empty message

Revision ID: 8968be7505a5
Revises: 504454e11680
Create Date: 2023-10-11 12:20:55.628972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8968be7505a5'
down_revision = '504454e11680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'create_date')
    # ### end Alembic commands ###
