"""empty message

Revision ID: 8de791403d24
Revises: b3eab94585de
Create Date: 2023-10-05 19:16:33.406050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8de791403d24'
down_revision = 'b3eab94585de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advances', sa.Column('offline_pid', sa.Integer(), nullable=True, comment='Локальний номер чека оффлайн'))
    op.add_column('inkasses', sa.Column('offline_pid', sa.Integer(), nullable=True, comment='Локальний номер чека оффлайн'))
    op.add_column('offline_checks', sa.Column('offline_pid', sa.Integer(), nullable=True, comment='Локальний номер чека оффлайн'))
    op.add_column('podkreps', sa.Column('offline_pid', sa.Integer(), nullable=True, comment='Локальний номер чека оффлайн'))
    op.add_column('sales', sa.Column('offline_pid', sa.Integer(), nullable=True, comment='Локальний номер чека оффлайн'))
    op.add_column('shifts', sa.Column('offline_pid', sa.Integer(), nullable=True, comment='Локальний номер чека оффлайн'))
    op.add_column('stornos', sa.Column('offline_pid', sa.Integer(), nullable=True, comment='Локальний номер чека оффлайн'))
    op.add_column('z_reports', sa.Column('offline_pid', sa.Integer(), nullable=True, comment='Локальний номер чека оффлайн'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('z_reports', 'offline_pid')
    op.drop_column('stornos', 'offline_pid')
    op.drop_column('shifts', 'offline_pid')
    op.drop_column('sales', 'offline_pid')
    op.drop_column('podkreps', 'offline_pid')
    op.drop_column('offline_checks', 'offline_pid')
    op.drop_column('inkasses', 'offline_pid')
    op.drop_column('advances', 'offline_pid')
    # ### end Alembic commands ###
