"""empty message

Revision ID: 92fc195b3ff6
Revises: 6f330981535d
Create Date: 2023-05-26 13:49:34.259177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fc195b3ff6'
down_revision = '6f330981535d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_check', sa.Column('discount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Дисконт операції'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_check', 'discount')
    # ### end Alembic commands ###
