"""empty message

Revision ID: a0135f46b575
Revises: 48b210411f63
Create Date: 2021-12-22 23:43:32.557734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0135f46b575'
down_revision = '48b210411f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('prev_hash', sa.String(length=64), nullable=True, comment='Хэш предыдущего оффлайн документа'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'prev_hash')
    # ### end Alembic commands ###
