"""empty message

Revision ID: a6d47157d7bf
Revises: 661bbd8d248b
Create Date: 2022-09-12 21:59:12.683059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d47157d7bf'
down_revision = '661bbd8d248b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advances', sa.Column('doc_uid', sa.String(length=36), nullable=True, comment='UID'))
    op.add_column('inkasses', sa.Column('doc_uid', sa.String(length=36), nullable=True, comment='UID'))
    op.create_table_comment(
        'inkasses',
        'Таблица данных об инкассациях',
        existing_comment='Таблица данных о инкассациях',
        schema=None
    )
    op.add_column('podkreps', sa.Column('doc_uid', sa.String(length=36), nullable=True, comment='UID'))
    op.add_column('sales', sa.Column('doc_uid', sa.String(length=36), nullable=True, comment='UID'))
    op.add_column('shifts', sa.Column('doc_uid', sa.String(length=36), nullable=True, comment='UID'))
    op.add_column('stornos', sa.Column('doc_uid', sa.String(length=36), nullable=True, comment='UID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stornos', 'doc_uid')
    op.drop_column('shifts', 'doc_uid')
    op.drop_column('sales', 'doc_uid')
    op.drop_column('podkreps', 'doc_uid')
    op.create_table_comment(
        'inkasses',
        'Таблица данных о инкассациях',
        existing_comment='Таблица данных об инкассациях',
        schema=None
    )
    op.drop_column('inkasses', 'doc_uid')
    op.drop_column('advances', 'doc_uid')
    # ### end Alembic commands ###
