"""empty message

Revision ID: ac89228a19c3
Revises: bef138602367
Create Date: 2021-12-07 17:51:17.859752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac89228a19c3'
down_revision = 'bef138602367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_keys', 'key_tax_registered')
    op.add_column('departments', sa.Column('key_tax_registered', sa.Boolean(), nullable=True, comment='Ознака що ключ зареєстровано у податковій формою 5-ПРРО'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'key_tax_registered')
    op.add_column('department_keys', sa.Column('key_tax_registered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Ознака що ключ зареєстровано у податковій формою 5-ПРРО'))
    # ### end Alembic commands ###
