"""empty message

Revision ID: b3ca900c244f
Revises: e4b0f77ba3ba
Create Date: 2021-05-12 07:25:46.517898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3ca900c244f'
down_revision = 'e4b0f77ba3ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advances',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Отделение'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Пользователь'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='Время совершения операции'),
    sa.Column('shift_id', sa.Integer(), nullable=True, comment='Идентификатор смены'),
    sa.Column('fiscal_time', sa.DateTime(), nullable=True, comment='Время принятия фискальным сервером (для пРРО)'),
    sa.Column('server_time', sa.DateTime(), nullable=True, comment='Время отправки на фискальный сервер (для пРРО)'),
    sa.Column('sum', sa.Numeric(precision=20, scale=2), nullable=True, comment='Сумма'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='Локальный номер чека'),
    sa.Column('tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека'),
    sa.Column('xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое отправляемого чека'),
    sa.Column('fiscal_xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое чека как его видит налоговая'),
    sa.Column('fiscal_ticket', sa.TEXT(), nullable=True, comment='Текстовое содержимое ответа налоговой'),
    sa.Column('fiscal_error_code', sa.Integer(), nullable=True, comment='Код ошибки'),
    sa.Column('fiscal_error_txt', sa.TEXT(), nullable=True, comment='Текст ошибки'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о полученных авансах'
    )
    op.create_table('inkasses',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Отделение'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Пользователь'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='Время совершения операции'),
    sa.Column('shift_id', sa.Integer(), nullable=True, comment='Идентификатор смены'),
    sa.Column('fiscal_time', sa.DateTime(), nullable=True, comment='Время принятия фискальным сервером (для пРРО)'),
    sa.Column('server_time', sa.DateTime(), nullable=True, comment='Время отправки на фискальный сервер (для пРРО)'),
    sa.Column('sum', sa.Numeric(precision=20, scale=2), nullable=True, comment='Сумма'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='Локальный номер чека'),
    sa.Column('tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека'),
    sa.Column('xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое отправляемого чека'),
    sa.Column('fiscal_xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое чека как его видит налоговая'),
    sa.Column('fiscal_ticket', sa.TEXT(), nullable=True, comment='Текстовое содержимое ответа налоговой'),
    sa.Column('fiscal_error_code', sa.Integer(), nullable=True, comment='Код ошибки'),
    sa.Column('fiscal_error_txt', sa.TEXT(), nullable=True, comment='Текст ошибки'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о инкассациях'
    )
    op.create_table('podkreps',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Отделение'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Пользователь'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='Время совершения операции'),
    sa.Column('shift_id', sa.Integer(), nullable=True, comment='Идентификатор смены'),
    sa.Column('fiscal_time', sa.DateTime(), nullable=True, comment='Время принятия фискальным сервером (для пРРО)'),
    sa.Column('server_time', sa.DateTime(), nullable=True, comment='Время отправки на фискальный сервер (для пРРО)'),
    sa.Column('sum', sa.Numeric(precision=20, scale=2), nullable=True, comment='Сумма'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='Локальный номер чека'),
    sa.Column('tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека'),
    sa.Column('xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое отправляемого чека'),
    sa.Column('fiscal_xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое чека как его видит налоговая'),
    sa.Column('fiscal_ticket', sa.TEXT(), nullable=True, comment='Текстовое содержимое ответа налоговой'),
    sa.Column('fiscal_error_code', sa.Integer(), nullable=True, comment='Код ошибки'),
    sa.Column('fiscal_error_txt', sa.TEXT(), nullable=True, comment='Текст ошибки'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о подкреплениях'
    )
    op.drop_table('company_keys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_keys',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='Iдентифікатор'),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True, comment='Назва'),
    sa.Column('public_key', mysql.VARCHAR(length=100), nullable=True, comment='Ідентифікатор відкритого ключа'),
    sa.Column('create_date', mysql.DATETIME(), nullable=True),
    sa.Column('key_password', mysql.VARCHAR(length=100), nullable=False, comment='Пароль захисту ключа'),
    sa.Column('begin_time', mysql.DATETIME(), nullable=True, comment='Время выдачи ключа'),
    sa.Column('end_time', mysql.DATETIME(), nullable=True, comment='Время окончания ключа'),
    sa.Column('key_data', sa.BLOB(), nullable=True, comment='Содержимое файла ключа'),
    sa.Column('key_data_txt', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True, comment='Текстовое содержимое файла ключа'),
    sa.Column('cert1_data', sa.BLOB(), nullable=True, comment='Содержимое файла 1 сертификата'),
    sa.Column('cert2_data', sa.BLOB(), nullable=True, comment='Содержимое файла 2 сертификата'),
    sa.Column('key_content', mysql.VARCHAR(length=4096), nullable=True, comment='Распакованное содержимое криптоключа'),
    sa.Column('box_id', mysql.VARCHAR(length=100), nullable=True, comment='Идентификатор крипто-сессии'),
    sa.Column('key_role', mysql.VARCHAR(length=10), nullable=True, comment='Роль ключа'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник ключей ЭЦП компаний',
    mysql_comment='Справочник ключей ЭЦП компаний',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('podkreps')
    op.drop_table('inkasses')
    op.drop_table('advances')
    # ### end Alembic commands ###
