"""empty message

Revision ID: bdb95357d917
Revises: e4b3e4a2799c
Create Date: 2021-12-22 12:36:18.822252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb95357d917'
down_revision = 'e4b3e4a2799c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('auto_close_time', sa.Time(), nullable=True, comment='Час автоматичного закриття зміни'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'auto_close_time')
    # ### end Alembic commands ###
