"""empty message

Revision ID: dca3b043b12d
Revises: f7ba5a805d79
Create Date: 2023-06-06 17:06:45.238038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca3b043b12d'
down_revision = 'f7ba5a805d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('offline_prev_hash', sa.String(length=64), nullable=True, comment='Геш попереднього офлайн документа'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'offline_prev_hash')
    # ### end Alembic commands ###
