"""empty message

Revision ID: e4b0f77ba3ba
Revises: 09d3796cd306
Create Date: 2021-05-11 08:57:13.702386

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4b0f77ba3ba'
down_revision = '09d3796cd306'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('shift_id', sa.Integer(), nullable=True, comment='Идентификатор смены'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'shift_id')
    # ### end Alembic commands ###
