"""empty message

Revision ID: eba2ba33745e
Revises: 19ef725b994d
Create Date: 2021-08-03 10:50:27.328550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eba2ba33745e'
down_revision = '19ef725b994d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('ret', sa.Boolean(), nullable=True, comment='Признак возврата'))
    op.add_column('sales', sa.Column('orderretnum', sa.Integer(), nullable=True, comment='Фискальный номер чека возврата'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'orderretnum')
    op.drop_column('sales', 'ret')
    # ### end Alembic commands ###
