"""empty message

Revision ID: ebc73e720c05
Revises: 92fc195b3ff6
Create Date: 2023-05-26 18:00:51.150349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc73e720c05'
down_revision = '92fc195b3ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('discount', sa.Numeric(precision=20, scale=2), nullable=True, comment='Дисконт'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'discount')
    # ### end Alembic commands ###
