"""empty message

Revision ID: ebe49be57b9d
Revises: ac89228a19c3
Create Date: 2021-12-07 22:34:52.707585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebe49be57b9d'
down_revision = 'ac89228a19c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department_keys', sa.Column('email', sa.String(length=50), nullable=True, comment='Електронна пошта для надсилання звітів'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department_keys', 'email')
    # ### end Alembic commands ###
