"""empty message

Revision ID: f7ba5a805d79
Revises: 456eec135b5a
Create Date: 2023-06-06 13:07:54.971258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ba5a805d79'
down_revision = '456eec135b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('offline_session_duration', sa.Integer(), nullable=True, comment='Тривалість оффлайн сесії'))
    op.add_column('departments', sa.Column('offline_session_monthly_duration', sa.Integer(), nullable=True, comment='Тривалість оффлайн сесії з початку місяця'))
    op.add_column('departments', sa.Column('last_offline_session_start', sa.DateTime(), nullable=True, comment='Час початку оффлайн сесії'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'last_offline_session_start')
    op.drop_column('departments', 'offline_session_monthly_duration')
    op.drop_column('departments', 'offline_session_duration')
    # ### end Alembic commands ###
