"""empty message

Revision ID: f8120fc0cdd3
Revises: 4a2d38893f17
Create Date: 2021-12-28 14:49:31.728692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8120fc0cdd3'
down_revision = '4a2d38893f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stornos',
    sa.Column('id', sa.Integer(), nullable=False, comment='Iдентифікатор'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='Отделение'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='Пользователь'),
    sa.Column('operation_time', sa.DateTime(), nullable=True, comment='Время совершения операции'),
    sa.Column('shift_id', sa.Integer(), nullable=True, comment='Идентификатор смены'),
    sa.Column('fiscal_time', sa.DateTime(), nullable=True, comment='Время принятия фискальным сервером (для пРРО)'),
    sa.Column('server_time', sa.DateTime(), nullable=True, comment='Время отправки на фискальный сервер (для пРРО)'),
    sa.Column('sum', sa.Numeric(precision=20, scale=2), nullable=True, comment='Сумма'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='Локальный номер чека'),
    sa.Column('tax_id', sa.Integer(), nullable=True, comment='Фискальный номер чека'),
    sa.Column('xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое отправляемого чека'),
    sa.Column('fiscal_xml', sa.TEXT(), nullable=True, comment='Текстовое содержимое чека как его видит налоговая'),
    sa.Column('fiscal_ticket', sa.TEXT(), nullable=True, comment='Текстовое содержимое ответа налоговой'),
    sa.Column('fiscal_error_code', sa.Integer(), nullable=True, comment='Код ошибки'),
    sa.Column('fiscal_error_txt', sa.TEXT(), nullable=True, comment='Текст ошибки'),
    sa.Column('original_tax_id', sa.Integer(), nullable=True, comment='Фискальный номер сторнируемого чека'),
    sa.Column('testing', sa.Boolean(), nullable=True, comment='Ознака тестового нефіскального документа'),
    sa.Column('offline_fiscal_xml_signed', sa.LargeBinary(), nullable=True, comment='Вміст файлу XML з сертифікатом підпису'),
    sa.Column('offline_check', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'),
    sa.Column('offline_tax_id', sa.String(length=32), nullable=True, comment='Фискальный номер чека оффлайн'),
    sa.Column('offline', sa.Boolean(), nullable=True, comment='Чек сохранен в режиме оффлайн'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Таблица данных о чеках сторно'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stornos')
    # ### end Alembic commands ###
